### listQueues
GET http://localhost:3000/queue/listQueues HTTP/1.1

### getQueueUrl
POST http://localhost:3000/queue/getQueueUrl HTTP/1.1
Content-Type: application/json

{
    "QueueName": "q_ps"
}

### sendMessage
POST http://localhost:3000/queue/sendMessage HTTP/1.1
Content-Type: application/json

{
    "QueueUrl": "https://sqs.eu-central-1.amazonaws.com/201448095557/q_ps",
    "MessageAttributes": {
        "Title": {
            "DataType": "String",
            "StringValue": "The Whistler"
        },
        "Author": {
            "DataType": "String",
            "StringValue": "John Grisham"
        },
        "WeeksOn": {
            "DataType": "Number",
            "StringValue": "6"
        }
    },
    "MessageBody": "Information about current NY Times fiction bestseller for week of 12/11/2016."
}

### receiveMessage
POST http://localhost:3000/queue/receiveMessage HTTP/1.1
Content-Type: application/json

{
    "MessageAttributeNames": [
        "All"
    ],
    "QueueUrl": "https://sqs.eu-central-1.amazonaws.com/201448095557/q_ps"
}

### listStoredMessages
GET http://localhost:3000/queue/listStoredMessages HTTP/1.1
