### listQueues
GET http://localhost:3000/queue/listQueues HTTP/1.1

### getQueueUrl
POST http://localhost:3000/queue/getQueueUrl HTTP/1.1
Content-Type: application/json

{
    "QueueName": "fifo_queue.fifo"
}

### sendMessage
POST http://localhost:3000/queue/sendMessageFifo HTTP/1.1
Content-Type: application/json

{
    "QueueUrl": "https://sqs.eu-central-1.amazonaws.com/201448095557/fifo_queue.fifo",
    "MessageGroupId": "newgroup",
    "MessageAttributes": {
        "Title": {
            "DataType": "String",
            "StringValue": "The Whistlerr"
        },
        "Author": {
            "DataType": "String",
            "StringValue": "John Grishamm"
        },
        "WeeksOn": {
            "DataType": "Number",
            "StringValue": "66"
        }
    },
    "MessageBody": "Informationn about current NY Times fiction bestseller for week of 12/11/2016."
}

### receiveMessage
POST http://localhost:3000/queue/receiveMessage HTTP/1.1
Content-Type: application/json

{
    "MessageAttributeNames": [
        "All"
    ],
    "QueueUrl": "https://sqs.eu-central-1.amazonaws.com/201448095557/fifo_queue.fifo"
}
